# Overrides the default URL, needed for your atom feed and sitemap
url: https://ellisv.github.io

# Restoring keep_files to default value
keep_files: ~

# Hides your drafts and future posts
future: false
show_drafts: false
# Gives you more accurate related posts
lsi: true
# Removes the upper limit for posts generated
limit_posts: 0
